apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: springbootdemo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: springbootdemo
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 50